### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by dayanare** [Adalab/modulo-2-evaluacion-intermedia-miranda-zapata#1]
Some improvements

Really cool job @miranda-zapata !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [ ] Enable Strict mode by writing `'use strict'` at the beginning of the js document.
- [x] Execute `getRandomNumber` function when the user clicks on "Jugar" button.
- [x] If you call `getRandomNumber` function outside the event callback, you will be creating a new random number when the page loads. That makes the game really simple and the hints will have the same result. Let's generate the random number when the user clicks on "Jugar" button and starts the round.
- [x] Extract the feedback painter to a function.
- [x] Remove debugger and other unnecessary code https://github.com/Adalab/modulo-2-evaluacion-intermedia-miranda-zapata/blob/main/js/main.js#L52
 
### JavaScript: advanced

- [x] Check if the `<select>` has the default option (with no value).

### HTML

- [x] Don't leave attributes with empty value.

### CSS

- [ ] Avoid adding styles until the js code is solid as a rock.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Check if the player has enough money to bet and if the bet is greater than 0 and lower than the current amount of the player.
- Add a reset button that cleans the select, balance of money and writes the initial feedback. 
- Show the restart game button when the game is over and hide the play button. 
- Complete the code needed for the restart game button. 
- Validates if the balance of money is available is less than the money bet and displays a message
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by heyDevMiranda** [comment]
- [x] 'use strict' was already enabled, checked.
- [x] Changed the execution of the getRandomNumber function so the game is purely "throw dice and bet", not a "guess the number" as was initially (and intentionally) coded.
- [x] Painted the random number generated so user knows there's no cheating.
- [x] Extracted all feedback painters to functions.
- [x] Decided to leave the CSS style because it was short and simple, and was done after the compulsory JS coding was done (so as a bonus).
- [x] Further challenges: I might come back to these later...! ^__^!

Thank you so much for the feedback!
